### ISSUE TITLE
EPIC: Refactor Tagging Contract

### ISSUE THREAD

**Issue by mpaler** [ethereum-tag-service/ets#24]
**EPIC**

In the parlance of the Service, the "target" is the digital artifact, addressable by a URI of some sort, that is being tagged by an ETSTag (NFT). The current ETS tagging contract has a number of drawbacks in the way tag targets are handled. That tagging contract / target handling is the focus of this Epic.

**The Problems**
 
1. **Target type is limited to NFTs.**
See #18 
A generalized tagging contract should support theoretically any addressable online artifact. (URL, Tweet, Jpeg, tranaction record, NFTs, etc, etc.) If it's online, we should be able to tag it. Currently ETS only supports tagging of NFTs.
2. **Tagging targets are not treated as a first class citizen (entity) by the Service.** 
See #18 
Currently, every time a target is tagged, we store all of the target information both in the blockchain and in the graph, over and over. This defeats DRY programming. A better solution is to turn targets into a recognizable entity/object within the Service, identifiable by a unique identifier.
3. **Target is not verified and it's metadata not stored in a scalable/systematic way.**
See #5
Currently, the tagging contract accepts the minimum necessary information about a NFT target in order to address it: contract, tokenid, chainid. Using these, the  Service leaves it up to the client to take those and extract any important metadata (image, title, description, etc) for the presentation layer. This sucks in many ways, especially for publishers looking to implement the Service.
4. **Targets may only be tagged one at a time with one tag at a time.**
See #27 
A tagging service of any value to publishers should do better than this and support a variety of tagging scenarios including:
    1. tagging a single target with one or more tags
    2. tagging multiple targets with one or more tags
5. **There are no facilities to untag targets.**
See #8 
A proper tagging protocol should be able to both tag and untag targets. Untagging should also be able to be done in bulk.
6. **There is no scalable way to tag on behalf of the tagger.** 
See #16 
In other words as a publisher, I want to recognize a user address as the tagger, while I pay for the transaction as the publisher (this makes be the tag Sponsor). To do this in a secure way, we need a way to allow the tagger to sign a transaction while the publisher pays for it. aka meta transactions.

### Child issues:

- [x] Refactor subgraph to reflect refactored smart contracts #38
- [x] Update HTP contracts & Tests to use ETS naming #32
- [x] Multi tag and target tagging #27
- [x] Turn tag target into a ETS first class citizen #18
- [x] Add Sponsor participant role to smart contracts #16
- [x] Add/remove tags functionality aka `updateTaggingRecord()` #8
- [x] Ensuring targets #5
- [x] Add/remove tags functionality aka updateTaggingRecord() #97
- [x] Unify ETSTag, Target & Tagging Record creation / id pattern #96
- [x] Add natspec documentation to ETS contracts  #104
