### ISSUE TITLE
EPIC: Core ETS tests

### ISSUE THREAD

**Issue by mpaler** [ethereum-tag-service/ets#69]
As the service, we would like to unit test the v2 architecture with a target code coverage of 100% for our core contracts.

http://www.correccionesweb.com.ar/hardhat_vue/plugins/solidity-coverage.html
https://medium.com/edgefund/testing-and-code-coverage-of-solidity-smart-contracts-660cb6291701

This issue will cover all testing except the ETSEnsure contracts & offchain service, which will be covered in #70 

### Child issues:

- [x] Install and enable solidity coverage module for tests #75
- [ ] Tests: ETSAccessControls.sol testing #72
- [ ] Tests: ETSEnsure #70
- [ ] Tests: ETSTag.sol testing #73
- [ ] Tests: ETS.sol testing #74
